[package]
name = "rzboard-etch"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.11", features = ["derive", "string"] }
log = "0.4.20"
pretty_env_logger = "0.5.0"
zip = "0.6.6"
